site_name: Code Notes
site_description: A personal collection of insights and practical tips on various programming topics.
site_author: Carlos Santos
site_url: https://code-notes.casantosmu.com
repo_url: https://github.com/casantosmu/code-notes

nav:
  - Home: index.md
  - Patterns:
      - Understanding State Machines: patterns/finite-state-machines.md
  - SQL:
      - Standard Data Types: sql/standard-data-types.md
      - Standard Functions: sql/standard-functions.md
  - PostgreSQL:
      - Setting Up: postgresql/setting-up.md
  - Ubuntu Server:
      - Setting Up: ubuntu-server/setting-up.md
      - Cloudflare and Nginx: ubuntu-server/cloudflare-nginx.md
      - Remove Packages: ubuntu-server/remove-packages.md
  - Resources: resources.md

theme:
  name: material
  favicon: assets/favicon.png
  icon:
    logo: material/file-document
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy

plugins:
  - privacy
  - search
  - git-revision-date-localized
  - minify:
      minify_html: true
  - meta-descriptions:
      enable_checks: true

markdown_extensions:
  - toc:
      permalink: true

  # Admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  # Code blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn
